name: release

permissions:
  contents: write
  deployments: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
      dry_run:
        description: "Dry run"
        required: true
        type: boolean
        default: true

jobs:
  update-repo:
    name: Update kubetail-nix repo with new version
    environment: production
    runs-on: ubuntu-24.04
    steps:
      - name: Config
        id: config
        run: |
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "dry_run=${{ github.event.inputs.dry_run }}" >> $GITHUB_OUTPUT
          echo "tag_name=${{ github.event.inputs.version }}-1" >> $GITHUB_OUTPUT

      - name: Download SHA256SUMS
        id: release-info
        uses: robinraju/release-downloader@v1.12
        with:
          repository: kubetail-org/kubetail
          tag: ${{ format('cli/v{0}', steps.config.outputs.version) }}
          fileName: "SHA256SUMS"
          out-file-path: "downloads"

      - name: Extract shasum
        id: meta
        working-directory: ./downloads
        run: |
          set -euo pipefail

          SHA256=$( tr -d '\r' < './SHA256SUMS' | awk '$2 == "kubetail-cli.orig.tar.xz" {print $1}' )

          # Convert hex digest to SRI base64 required by Nix hash attribute.
          SHA256_SRI=$(printf '%s' "$SHA256" | xxd -r -p | base64 | tr -d '\n')

          echo "sha256=$SHA256_SRI" >> $GITHUB_OUTPUT

      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            .github/ci-config/default.nix.tmpl
            default.nix
          sparse-checkout-cone-mode: false

      - name: Execute templates
        env:
          VERSION: ${{ steps.config.outputs.version }}
          SHA256: ${{ steps.meta.outputs.sha256 }}
        run: |
          set -euo pipefail

          envsubst '${VERSION} ${SHA256}' \
            < .github/ci-config/default.nix.tmpl \
            > default.nix

      - name: Configure gpg
        uses: crazy-max/ghaction-import-gpg@v6.3.0
        with:
          gpg_private_key: ${{ secrets.KUBETAIL_BOT_PGP_SIGNING_KEY }}
          passphrase: ${{ secrets.KUBETAIL_BOT_PGP_PASSWORD }}

      - name: Configure git
        run: |
          git config gpg.program gpg
          git config commit.gpgsign true

          git config user.name "${{ vars.KUBETAIL_BOT_NAME }}"
          git config user.email "${{ vars.KUBETAIL_BOT_EMAIL }}"
          git config user.signingkey "${{ vars.KUBETAIL_BOT_PGP_FINGERPRINT }}"

      - name: Debug
        if: ${{ steps.config.outputs.dry_run == 'true' }}
        run: |
          cat default.nix

      - name: Merge into main and tag commit
        if: ${{ steps.config.outputs.dry_run != 'true' }}
        run: |
          # Stage changes
          git add default.nix

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          # Commit and push
          git commit -a -s -m "release: ${{ steps.config.outputs.tag_name }}"
          git push origin

          # Tag and push
          git tag -s "${{ steps.config.outputs.tag_name }}" -m "release: ${{ steps.config.outputs.tag_name }}"
          git push origin --tags

      - name: Create GitHub release
        if: ${{ steps.config.outputs.dry_run != 'true' }}
        uses: softprops/action-gh-release@v2.4.1
        with:
          draft: false
          name: "${{ steps.config.outputs.tag_name }}"
          body: "Release: `kubetail` ${{ steps.config.outputs.version }}"
          tag_name: "${{ steps.config.outputs.tag_name }}"
          make_latest: true
